### DISCUSSION TITLE
ADR 008: Adopt fallback mechanism

### DISCUSSION THREAD

**Discussion by bmf-san** [bmf-san/gondola#74] [Architecture Decision Record]
Here’s the translation for the new request:

---

### Title  
Adopt Fallback Mechanism

### Context  
In a reverse proxy, maintaining a good user experience when upstream servers are unavailable or failures occur is important. A fallback mechanism is a critical feature that improves system fault tolerance and enhances the user experience.

### Decision  
It has been decided to implement a fallback mechanism with the following features:

- **Upstream failure detection:** Early detection of failures through health checks.
- **Multiple fallback options:**
  - Forwarding to alternative upstream servers
  - Serving static content
  - Displaying custom error pages
- **Flexible configuration:** YAML-based settings to customize fallback behavior for each path or host.

```yaml
proxy:
  fallback:
    enabled: true
    health_check:
      interval: "10s"
      timeout: "5s"
      healthy_threshold: 2
      unhealthy_threshold: 3
    
    upstreams:
      - host: "primary.example.com"
        fallback_to:
          - "backup1.example.com"
          - "backup2.example.com"
        static_fallback: "/fallback"
        cache_ttl: "1h"
    
    paths:
      - path: "/api"
        fallback_to: "api-backup.example.com"
      - path: "/static"
        static_fallback: "/local-static"
```

### Status  
Accepted

#### Positive
- Increased system availability
- Maintained user experience
- Flexible response to failures
- Reduced operational costs

#### Negative
- Increased complexity in configuration
- Need for testing fallback logic
- Additional storage requirements (for static fallback content)
