### DISCUSSION TITLE
ADR 009: Graceful shutdown

### DISCUSSION THREAD

**Discussion by bmf-san** [bmf-san/gondola#76] [Architecture Decision Record]
### Title  
Implement Graceful Shutdown Mechanism

### Context  
In the operation of a reverse proxy, there are times when it is necessary to stop the service for maintenance or deployment. However, abrupt shutdowns can interrupt ongoing requests and negatively affect the user experience. Additionally, if connections to upstream servers are not properly terminated, resource leaks or data integrity issues may arise.

### Decision  
It has been decided to implement a graceful shutdown mechanism with the following features:

1. **Shutdown Settings:**

```yaml
proxy:
  shutdown:
    # Maximum wait time until shutdown completion
    timeout: "30s"
    # Time to wait for the completion of existing requests after stopping acceptance of new connections
    drain_timeout: "10s"
    # Change in health check status when shutdown starts
    health_check_critical_on_shutdown: true
```

2. **Shutdown Phases:**
   - Stop accepting new connections
   - Update health check status
   - Wait for the completion of existing requests
   - Properly terminate upstream connections
   - Clean up resources

3. **Signal Handling:**
   - **SIGTERM**: Start graceful shutdown
   - **SIGQUIT**: Immediate shutdown
   - **SIGHUP**: Reload configuration

### Status  
Accepted

#### Positive  
- Guarantees completion of ongoing requests  
- Proper cleanup of connections and resources  
- Minimizes downtime  
- Enhances the safety of deployments and maintenance  

#### Negative  
- Increased complexity of the shutdown process  
- Adjustment of timeout settings may be necessary  
- Temporary increase in memory usage  
- Potential for longer shutdown times

### References  
- [Golang http.Server Shutdown](https://pkg.go.dev/net/http#Server.Shutdown)  
- [Nginx Graceful Shutdown](https://nginx.org/en/docs/control.html#quit) 
- [Kubernetes Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)
