### ISSUE TITLE
Customizable Access Log Format Support

### ISSUE THREAD

**Issue by bmf-san** [bmf-san/gondola#68]
# Description

A feature is needed to customize the format of access logs via a configuration file. Currently, the JSON format of slog is fixed, but more flexible log output settings are required.

# Describe the feature you'd like to request

The following features are proposed:

- Ability to specify the access log format in the configuration file
  - JSON format
  - Apache Common Log format
  - Apache Combined Log format
  - Custom format (defined using template strings)
- Output destination settings
  - Standard output (default)
  - File output
  - Both
- Log rotation settings
  - File size-based
  - Time-based

# Describe the solution you'd like

### Add a new configuration structure in `config.go`

```yaml
log:
  format: "json"  # "json", "common", "combined", "custom"
  custom_format: '${remote_ip} ${method} ${uri} ${status}'  # Used when format is "custom"
  output:
    stdout: true
    file:
      enabled: false
      path: "/var/log/gondola/access.log"
      rotation:
        enabled: true
        type: "time"  # "time" or "size"
        max_size: "100MB"  # Used when type is "size"
        interval: "24h"    # Used when type is "time"
```

### Enhancements to `logger.go`

- Introduce a formatter interface
- Implement each format (JSON, Common, Combined, Custom)
- Implement log rotation functionality

### Available variables (for custom format)

- `${timestamp}`: Access time
- `${remote_ip}`: Client IP
- `${method}`: HTTP method
- `${uri}`: Request URI
- `${protocol}`: Protocol
- `${status}`: HTTP status code
- `${user_agent}`: User-Agent
- `${referer}`: Referer
- `${request_time}`: Request processing time
- `${trace_id}`: Trace ID
