### ISSUE TITLE
Connection pooling support

### ISSUE THREAD

**Issue by bmf-san** [bmf-san/gondola#73]
Here’s the translation in the requested format:

---

# Description

To improve performance and achieve efficient resource utilization, it is necessary to implement a connection pooling feature in Gondola. This will allow reusing connections to upstream servers, reducing the overhead of establishing connections.

# Describe the feature you'd like to request

- Connection pool implementation to upstream servers
- Flexible customization of pool settings
- Health check for connections
- Collection of pool metrics

# Describe the solution you'd like

Extend the configuration file:

```yaml
proxy:
  connection_pool:
    enable: true
    # Maximum number of idle connections per pool
    max_idle_conns: 100
    # Maximum idle time per connection
    max_idle_time: "5m"
    # Maximum lifetime of a connection
    max_lifetime: "30m"
    # Timeout for establishing a connection
    dial_timeout: "10s"
    # Health check interval
    health_check_interval: "30s"
    # Upstream settings
    upstreams:
      - host: "backend1.example.com"
        max_conns: 50
      - host: "backend2.example.com"
        max_conns: 30
```

Implementation requirements:

```go
type ConnectionPool struct {
    // Pool settings
    config PoolConfig
    // Map of active connections
    conns map[string][]*Connection
    // Mutex
    mu sync.RWMutex
}

type Connection struct {
    // Actual network connection
    conn net.Conn
    // Last used time
    lastUsed time.Time
    // Creation time
    created time.Time
    // Number of uses
    uses int64
}

type PoolConfig struct {
    MaxIdleConns        int
    MaxIdleTime        time.Duration
    MaxLifetime        time.Duration
    DialTimeout        time.Duration
    HealthCheckInterval time.Duration
}
```

Main Features:
- **Connection acquisition and return:**

```go
func (p *ConnectionPool) Get(host string) (*Connection, error)
func (p *ConnectionPool) Put(host string, conn *Connection)
```

- **Connection health check:**

```go
func (p *ConnectionPool) healthCheck()
func (p *ConnectionPool) isConnectionHealthy(conn *Connection) bool
```

- **Pool cleanup:**

```go
func (p *ConnectionPool) cleanup()
func (p *ConnectionPool) removeStaleConnections()
```

Error handling:
- Retry on connection establishment failure
- Removal of unhealthy connections based on health checks
- Creation of new connections when the pool is exhausted
- Timeout handling

Metrics:
- Number of active connections
- Pool size
- Connection wait times
- Connection error rate
- Pool usage rate
- Connection reuse rate

Optimization Strategies:
- Asynchronous connection establishment
- Backpressure implementation
- Adaptive pool sizing
- Load-based connection management
